#!/usr/bin/env python

import sys
import pylab

for arg in sys.argv[1:]:
    with open(arg) as f:
        lines = f.read().split('\n')
        if not lines:
            continue
        field_count = len(lines[0].split(','))
        for field in range(field_count):
            pylab.plot([float(line.split(',')[field].strip()) for line in lines
                if line.split(',')[0].strip()], antialiased=False)

pylab.show()
